### ISSUE TITLE
Types with Underscore not converted to CamelCase

### ISSUE THREAD

**Issue by Dav1dde** [kube-rs/kopium#109]
Rust Warning:

```
warning: type `FlowFiltersEnhanceK8sClient_key` should have an upper camel case name
   --> k8s-banzaicloud/src/flows.rs:271:12
    |
271 | pub struct FlowFiltersEnhanceK8sClient_key {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: convert the identifier to upper camel case: `FlowFiltersEnhanceK8sClientKey`
```

YAML:

```
                        client_key:
                          properties:
                            mountFrom:
                              properties:
                                secretKeyRef:
                                  properties:
                                    key:
                                      type: string
                                    name:
                                      type: string
                                    optional:
                                      type: boolean
```

Type generated: `FlowFiltersEnhanceK8sClient_key` and should be `FlowFiltersEnhanceK8sClientKey`

Can be reproduced with `kopium flows.logging.banzaicloud.io`
The CRD can be found here: https://github.com/kube-logging/logging-operator/blob/master/config/crd/bases/logging.banzaicloud.io_flows.yaml
