### ISSUE TITLE
duplicate fields generated

### ISSUE THREAD

**Issue by sebhoss** [kube-rs/kopium#165]
Calling `curl -sSL https://github.com/prometheus-operator/prometheus-operator/raw/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml | kopium -Af - > podmonitors.rs` generates the following output:

```rust
/// RelabelConfig allows dynamic rewriting of the label set for targets, alerts, scraped samples and remote write samples. 
///  More info: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema)]
pub enum PodMonitorPodMetricsEndpointsMetricRelabelingsAction {
    #[serde(rename = "replace")]
    Replace,
    Replace,
    #[serde(rename = "keep")]
    Keep,
    Keep,
    #[serde(rename = "drop")]
    Drop,
    Drop,
    #[serde(rename = "hashmod")]
    Hashmod,
    HashMod,
    #[serde(rename = "labelmap")]
    Labelmap,
    LabelMap,
    #[serde(rename = "labeldrop")]
    Labeldrop,
    LabelDrop,
    #[serde(rename = "labelkeep")]
    Labelkeep,
    LabelKeep,
    #[serde(rename = "lowercase")]
    Lowercase,
    Lowercase,
    #[serde(rename = "uppercase")]
    Uppercase,
    Uppercase,
    #[serde(rename = "keepequal")]
    Keepequal,
    KeepEqual,
    #[serde(rename = "dropequal")]
    Dropequal,
    DropEqual,
}
```

The problem here is that the upstream CRD actually defines all of those - once in lower case and once in camel case. Maybe camel case can be converted to snake case and attributed with serde rename to the original camel case version?

edit: nvm that idea does not work for single words like `replace`/`Replace`..

**Comment by clux** [comment]
```yaml
                          action:
                            default: replace
                            description: "Action to perform based on the regex matching.
                              \n `Uppercase` and `Lowercase` actions require Prometheus
                              >= v2.36.0. `DropEqual` and `KeepEqual` actions require
                              Prometheus >= v2.41.0. \n Default: \"Replace\""
                            enum:
                            - replace
                            - Replace
                            - keep
                            - Keep
                            - drop
                            - Drop
                            - hashmod
                            - HashMod
                            - labelmap
                            - LabelMap
                            - labeldrop
                            - LabelDrop
                            - labelkeep
                            - LabelKeep
                            - lowercase
                            - Lowercase
                            - uppercase
                            - Uppercase
                            - keepequal
                            - KeepEqual
                            - dropequal
                            - DropEqual
                            type: string
```

oh no
