### ISSUE TITLE
Status struct is not generated if the object is empty, but preserve-unknown-fields is true

### ISSUE THREAD

**Issue by zsoli69** [kube-rs/kopium#275]
In case a CRD has a status property defined as the following, the status struct will not be generated.

```yaml
status:
    description: Status description
    type: object
    x-kubernetes-preserve-unknown-fields: true
```
