### ISSUE TITLE
Lack of mangling for non-identifier properties

### ISSUE THREAD

**Issue by jcaesar** [kube-rs/kopium#38]
I encountered a crd [in the wild](https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.28.0/strimzi-cluster-operator-0.28.0.yaml) that contains the following snippet:
```yaml
              jvmOptions:
                description: JVM Options for pods.
                properties:
                  -XX:
                    description: A map of -XX options to the JVM.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  -Xms:
                    description: -Xms option to to the JVM.
                    pattern: ^[0-9]+[mMgG]?$
                    type: string

```
(Read with care, Github's highlighter is wrong here. This is not a list.)

which results in the following panic:
```plain
thread 'main' panicked at '"-XX" is not a valid Ident', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.36/src/fallback.rs:708:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.59.0/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/1.59.0/library/core/src/panicking.rs:116:14
   2: proc_macro2::fallback::validate_ident
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.36/src/fallback.rs:708:9
   3: proc_macro2::fallback::Ident::_new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.36/src/fallback.rs:642:9
   4: proc_macro2::fallback::Ident::new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.36/src/fallback.rs:652:9
   5: proc_macro2::imp::Ident::new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.36/src/wrapper.rs:691:50
   6: proc_macro2::Ident::new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.36/src/lib.rs:952:21
   7: quote::__private::mk_ident
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.15/src/runtime.rs:404:17
   8: kopium::Kopium::generate::{{closure}}
             at ./src/main.rs:189:29
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1.59.0/library/core/src/future/mod.rs:84:19
  10: kopium::Kopium::dispatch::{{closure}}
             at ./src/main.rs:116:41
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1.59.0/library/core/src/future/mod.rs:84:19
  12: kopium::main::{{closure}}
             at ./src/main.rs:106:35
[…tokio cruft…]
```

I think, in general, it would be nice to have some kind of name mangling that converts all identifiers to nice camel_case. Might require `#[serde(rename = "…")]` on all fields.
