### ISSUE TITLE
ServiceMonitor generates invalid maps

### ISSUE THREAD

**Issue by clux** [kube-rs/kopium#61]
Running:

```sh
curl -sSL https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml  \
  |  kopium -f - -A > servicemonito.rs
```

with a very small member:

```yaml
   params:
        additionalProperties:
          items:
            type: string
          type: array
        description: Optional HTTP URL parameters
        type: object
```

results in an invalid entry:

```rust
pub struct ServiceMonitorEndpoints {
    /// ...
    /// Optional HTTP URL parameters
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<BTreeMap<String, ServiceMonitorEndpointsParams>>,
    /// ...
}
```

where there's obviously no `ServiceMonitorEndpointsParams`. it should be map String -> String
