### ISSUE TITLE
empty `type` field is not handled

### ISSUE THREAD

**Issue by kodemaniak** [kube-rs/kopium#73]
When trying to generate code for the cert-manager `ClusterIssuer` CRD, kopium fails with:

```bash
$ kopium clusterissuers.cert-manager.io
Error: unknown empty dict type for config
```

It seems that the CRD contains a field that has no `type` set (`config`):

```yaml
                              webhook:
                                description: Configure an external webhook based DNS01 challenge solver to manage DNS01 challenge records.
                                type: object
                                required:
                                  - groupName
                                  - solverName
                                properties:
                                  config:
                                    description: Additional configuration that should be passed to the webhook apiserver when challenges are processed. This can contain arbitrary JSON data. Secret values should not be specified in this stanza. If secret values are needed (e.g. credentials for a DNS service), you should use a SecretKeySelector to reference a Secret resource. For details on the schema of this field, consult the webhook provider implementation's documentation.
                                    x-kubernetes-preserve-unknown-fields: true
                                  groupName:
                                    description: The API group name that should be used when POSTing ChallengePayload resources to the webhook apiserver. This should be the same as the GroupName specified in the webhook provider implementation.
                                    type: string
                                  solverName:
                                    description: The name of the solver to use, as defined in the webhook provider implementation. This will typically be the name of the provider, e.g. 'cloudflare'.
                                    type: string

```
Manually adding `type: object` makes kopium generate the code correctly.

I am actually not sure if this is allowed, but at least Kubernetes seems to accept emtpy `type` fields.
