### ISSUE TITLE
alertmanager crd crashes on empty enum string crd

### ISSUE THREAD

**Issue by clux** [kube-rs/kopium#93]
From their schema:
```yaml
              logFormat:
                description: Log format for Alertmanager to be configured with.
                enum:
                - ""
                - logfmt
                - json
```
this makes us want to create a variant with an empty name which does not work.

A suggested fix is to check for `name.is_empty()` and override it to `EmptyString` or something, but that runs the risk of clashing with other (potential) values in the enum (like if they had had an "empty" logformat). We could use a big KopiumEmptyString type thing, but that feels very ugly and wrong.

Another way to look at this is as just a degenerate case of #92, and this makes us use unspecified variant names for all elements instead. I think that's probably better (and less magic).
